stages:
  - install_dependencies
  - test
  - build_and_deliver

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  tags:
    - node
  script:
    - yarn install
  only:
    - merge_requests

lint:
  stage: test
  tags:
    - node
  script:
    - yarn lint
  only:
    - merge_requests

unit_test:
  stage: test
  tags:
    - node
  script:
    - yarn test:unit
  only:
    - merge_requests

build_production_pack:
  stage: build_and_deliver
  tags:
    - node
  script:
    - yarn build
    - cd dist
    - tar czf production.tar.gz *
  artifacts:
    paths:
      - dist/production.tar.gz
  only:
    - master
    - develop
    - merge_requests
