stages:
  - install_dependencies
  - test
  - build_and_deliver

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install_dependencies
  tags:
    - node
  script:
    - yarn install
  only:
    - merge_requests
    - master
    - develop

lint:
  stage: test
  tags:
    - node
  script:
    - yarn lint
  only:
    - merge_requests

unit_test_with_coverage:
  stage: test
  tags:
    - node
  script:
    - yarn test:unit --coverage
  only:
    - merge_requests
    - master
    - develop

build_production_pack:
  stage: build_and_deliver
  tags:
    - node
  script:
    - yarn build
  artifacts:
    name: production-pack
    paths:
      - dist/
  only:
    - master
    - develop
